### ISSUE TITLE
Handling events on list items

### ISSUE THREAD

**Issue by Tyrn** [Dirk-Sandberg/LiveStream-WhatsAppClone#1]
Hi,

How am I supposed to handle clicks/taps/presses on list items? It's a very real next iteration on this example. It probably has something to do with things like `ILeftBodyTouch`; unfortunately, I can't figure it out. Neither were I able to find an example.

**Comment by Dirk-Sandberg** [comment]
The list items inherit from `ButtonBehavior`, which means they have an `on_release` attribute just like a normal Button.

**Comment by Tyrn** [comment]
Thanks!

`on_release`, yes. Somehow, I haven't managed to make a lot of use of it. Here is the complete working app:

main.py:
```
from functools import partial
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout
from kivy.clock import Clock
from kivymd.app import MDApp
from kivymd.uix.tab import MDTabsBase
from kivymd.uix.list import OneLineListItem
from kivymd.uix.list import TwoLineAvatarIconListItem
from kivymd.icon_definitions import md_icons

class PowerListItem(OneLineListItem):
    """The engaged power supply item."""

    def on_touch_down(self, touch):
        if self.collide_point(*touch.pos):
            if touch.is_double_tap:
                tabs = MDApp.get_running_app().root.ids.android_tabs
                # Just like your on_release.
                tabs.tab_bar.parent.dispatch(
                    "on_tab_switch",
                    self.tab_details,
                    self.tab_details.tab_label,
                    md_icons[self.tab_details.text],
                )
                tabs.tab_bar.parent.carousel.load_slide(self.tab_details)
                return True
        return super(PowerListItem, self).on_touch_down(touch)

    def on_release(self):
        print("on release")


class TabList(FloatLayout, MDTabsBase):
    """The engaged power supplies tab."""

    def surfacing(self, tab_text):
        pass

    def discover(self, tab_details):
        for i in range(30):
            item = PowerListItem(text=f"Power supply {i + 1:>4}")
            item.tab_details = tab_details
            self.ids.container.add_widget(item)


class TabDetails(FloatLayout, MDTabsBase):
    """The engaged power supply details tab."""

    def surfacing(self, tab_text):
        self.ids.icon.icon = "equalizer"


class Contero(MDApp):
    def build(self):
        return Builder.load_file("main.kv")

    def on_start(self):
        text = "flash"
        main = TabList(text=text)
        main.surfacing(text)
        self.root.ids.android_tabs.add_widget(main)

        details = TabDetails(text="equalizer")
        self.root.ids.android_tabs.add_widget(details)
        Clock.schedule_once(lambda dt: main.discover(details), 5)

    def on_tab_switch(self, instance_tabs, instance_tab, instance_tab_label, tab_text):
        """Called when switching tabs.

        :type instance_tabs: <kivymd.uix.tab.MDTabs object>;
        :param instance_tab: <__main__.Tab object>;
        :param instance_tab_label: <kivymd.uix.tab.MDTabsLabel object>;
        :param tab_text: text or name icon of tab;
        """

        print(f"\ninstance_tab: {instance_tab}")
        print(f"instance_tab_label: {instance_tab_label}")
        print(f"tab_text: {tab_text}")
        instance_tab.surfacing(tab_text)


Contero().run()
```
main.kv:
```
BoxLayout:
    orientation: "vertical"

    #MDToolbar:
    #    title: "Example Tabs"

    MDTabs:
        id: android_tabs
        on_tab_switch: app.on_tab_switch(*args)


<TabList>:
    ScrollView:
        bar_margin: 5
        bar_width: 15
        bar_color: .0, .8, .0, 1
        bar_inactive_color: .5, .5, .5, 1
        effect_cls: "ScrollEffect"
        scroll_type: ["bars", "content"]
        scroll_distance: 5
        scroll_timeout: 250
        MDList:
            id: container


<TabDetails>:
    MDIconButton:
        id: icon
        user_font_size: "48sp"
        pos_hint: {"center_x": .5, "center_y": .5}
```
Is it inevitable, or I'm not seeing something obvious?
